[build]
  publish = "."

[[redirects]]
  from = "/calculadora"
  to = "/calculadora/index.html"
  status = 200

[[redirects]]
  from = "/calculadora/*"
  to = "/calculadora/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
